[package]
name = "restApi"
version = "0.1.0"
authors = ["wahyu setiawan <wahyu.creator911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
mysql = "18.2.0"
rusqlite = "0.23.1"